### ISSUE TITLE
PREVIEW_SECRET not working

### ISSUE THREAD

**Issue by lucafregoso** [strapi/strapi-starter-next-corporate#11]
I deployed the project on my local env, but the value i set for PREVIEW_SECRET is not read by Stripe which is always using  secret-token .
How to let Stripe get the env value?

**Comment by remidej** [comment]
Do you mean Strapi instead of Stripe?

If so, it may be because the value required by the backend is `FRONTEND_PREVIEW_SECRET`, not `PREVIEW_SECRET`

**Comment by lucafregoso** [comment]
Here you can see my two env files, but none of those values are read

<img width="1136" alt="Screenshot 2020-09-02 at 17 52 29" src="https://user-images.githubusercontent.com/184508/92006513-1c354180-ed45-11ea-9847-1040dc1a2d25.png">
<img width="1136" alt="Screenshot 2020-09-02 at 17 52 39" src="https://user-images.githubusercontent.com/184508/92006526-20615f00-ed45-11ea-92a6-bff5d035c39e.png">

**Comment by remidej** [comment]
Your environment files look good.

In the backend folder, try running `yarn build`, then start Strapi again.

Let me know if that fixes the issue
