### ISSUE TITLE
How to enable preview mode

### ISSUE THREAD

**Issue by pupudu** [strapi/strapi-starter-next-corporate#16]
Great starter kit, loving it already.

However, I faced one issue. In your blog video, it shows how we can click a button on a page to preview it with NextJs. I don't see that button on my strapi admin ui.

Is there something I need to do to enable that?

Many thanks 🙏🏼

**Comment by remidej** [comment]
Hello! Happy to hear you enjoy this starter.

I've addressed this issue over there: https://github.com/strapi/strapi-template-corporate/issues/1
