### ISSUE TITLE
Output directory different to that of Vercel

### ISSUE THREAD

**Issue by maggie44** [strapi/strapi-starter-next-corporate#19]
When deploying to Vercel the following settings were required:

<img width="773" alt="Screenshot 2021-01-20 at 20 44 23" src="https://user-images.githubusercontent.com/64841595/105281177-69814680-5b60-11eb-9000-e49c6cac653c.png">

Vercel's defaults are:

<img width="803" alt="Screenshot 2021-01-20 at 20 45 54" src="https://user-images.githubusercontent.com/64841595/105281229-887fd880-5b60-11eb-9bde-3bd97211a654.png">

Would suggest making the output directory Next.js.

**Comment by markkaylor** [comment]
Hi @maggie0002 according to Next.js documentation here: https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory the default build directory is `.next`.  So I don't think it is necessary to toggle the override here.   Did you have trouble when deploying?   I'm closing this issue for now, but please feel free to open if you are still having trouble.
