### ISSUE TITLE
No preview mode button

### ISSUE THREAD

**Issue by AdamDemirel** [strapi/strapi-starter-next-corporate#27]
Hi there, thanks for creating this starter project.

Unfortunately from a fresh install following all of the instructions in the README I end up with a Strapi instance which doesn't have a preview button. Am I missing something?

![image](https://user-images.githubusercontent.com/16191797/112774829-a1d46200-9086-11eb-9f6f-279cadb78d58.png)

This happens even if the page is in draft mode, and once the env variables are set.

Full video demonstrating from setup: https://streamable.com/8gw8c6

**Comment by remidej** [comment]
Hello Adam,

This is unfortunately normal, we removed that feature. I wrote a more detailed answer to that problem on the strapi-template-corporate repo: https://github.com/strapi/strapi-template-corporate/issues/1#issuecomment-744351066

**Comment by remidej** [comment]
Hey @AdamDemirel I'm also curious – where did you see that there should be a preview button? Was it on a blog article? Because it shouldn't be mentioned on the readme anymore

**Comment by icarillo** [comment]
Hi @remidej, I am just facing the same "issue" trying to find how to turn on the "Preview Mode".

>where did you see that there should be a preview button? Was it on a blog article? Because it shouldn't be mentioned on the readme anymore

I first read about the preview mode in the starter itself:
<img width="1346" alt="image1" src="https://user-images.githubusercontent.com/40901706/113469863-da1ccd00-9405-11eb-83a6-1cb295c9917e.png">

Then, searching how to use it, I found the following posts:
- https://strapi.io/blog/strapi-starter-next-corporate-site
- https://dev.to/dlw/using-next-js-preview-mode-with-strapi-cms-362n

**Comment by ingalless** [comment]
I think this can be fixed with the help from [this issue](https://github.com/strapi/strapi/issues/9384#issuecomment-852822144)

Is there any interest in a PR to fix this for Strapi `v3.6.x`?
